import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function readProjectFile(path) {
  return readFile(new URL(`../${path}`, import.meta.url), "utf8");
}

test("defines the Aquarius intro, origin story, music, and return flow", async () => {
  const source = await readProjectFile("app/aquarius-game.tsx");

  assert.match(source, /type IntroStep = "landing" \| "story" \| "setup"/);
  assert.match(source, /AQUARIUS_ORIGIN_STORY/);
  assert.match(source, /霓虹浮島/);
  assert.match(source, /FIND WEIRDO/);
  assert.match(source, /Developer: Jay Peng/);
  assert.doesNotMatch(source, /WEIRDO DETECTION SYSTEM/);
  assert.match(source, /MarqueeTags/);
  assert.match(source, /intro-audio-control/);
  assert.match(source, /aria-pressed=\{musicEnabled\}/);
  assert.match(source, /BGM_SRC = "\/audio\/lith-harbor-above-the-treetops\.mp3"/);
  assert.match(source, /SCRAMBLE_SFX_SRC = "\/audio\/noise-scramble\.mp3"/);
  assert.match(source, /startScrambleSfx/);
  assert.doesNotMatch(source, /FAIL_SFX_SRC/);
  assert.doesNotMatch(source, /playFailSound/);
  assert.match(source, /開始遊戲/);
  assert.doesNotMatch(source, />Skip</);
  assert.match(source, /story-pager/);
  assert.match(source, /story-arrow-button/);
  assert.match(source, /advanceStoryPage/);
  assert.match(source, /circle-back-button/);
  assert.match(source, /returnToSetupFromGame/);
});

test("normalizes avatar previews and removes starter preview assumptions", async () => {
  const [game, css, layout, page, packageJson, gameData, cityLayout] = await Promise.all([
    readProjectFile("app/aquarius-game.tsx"),
    readProjectFile("app/globals.css"),
    readProjectFile("app/layout.tsx"),
    readProjectFile("app/page.tsx"),
    readProjectFile("package.json"),
    readProjectFile("app/game-data.ts"),
    readProjectFile("app/city/city-layout.ts"),
  ]);

  assert.match(game, /mountAvatarPreview/);
  assert.match(game, /normalizedScale/);
  assert.match(game, /createFallbackPreviewAvatar/);
  assert.match(game, /createRuntimePlayerAvatarModel/);
  assert.match(game, /runtimePlayerAvatar/);
  assert.match(game, /getProceduralAvatarPalette/);
  assert.match(game, /PLAYER_AVATAR_RUNTIME_SCALE = 1/);
  assert.match(game, /PLAYER_RUNTIME_TARGET_HEIGHT = 1\.68/);
  assert.match(game, /normalizePlayerAvatarModel/);
  assert.match(game, /registerPlayerWalkParts/);
  assert.match(game, /applyPlayerWalkCycle/);
  assert.match(game, /PLAYER_FLOOR_OFFSET = 0\.48/);
  assert.match(game, /PLAYER_START = \{ x: 0, z: 26 \}/);
  assert.match(game, /hasRenderableMesh/);
  assert.match(game, /makePlayerNameLabel/);
  assert.doesNotMatch(game, /<figure className="avatar-preview-fallback"/);
  assert.match(game, /setDefaultCameraView\(runtime, true\)/);
  assert.match(game, /selectAdjacentAvatar/);
  assert.match(game, /avatar-mobile-switcher/);
  assert.match(game, /avatar-cycle-button/);
  assert.match(game, /aria-live="polite"\>\{selectedAvatarData\.title\}/);
  assert.match(game, /hasBlockingOverlay/);
  assert.match(game, /className=\{interactionLabel && !hasBlockingOverlay \? "mobile-action visible" : "mobile-action hidden"\}/);
  assert.match(game, /mobile-jump-icon/);
  assert.match(game, /shortcut-help/);
  assert.match(game, /quality-toggle/);
  assert.match(game, /繼續聽 <span className="desktop-key-hint">\(Space\)<\/span>/);
  assert.match(game, /確認 <span className="desktop-key-hint">\(Space\)<\/span>/);
  assert.match(game, /flying-cow/);
  assert.match(game, /signal-jellyfish/);
  assert.match(game, /createSkyWhale/);
  assert.match(game, /addAquariusLandmarks/);
  assert.match(game, /FOOD_PICKUPS/);
  assert.match(game, /showFloatingTimeBonus/);
  assert.match(game, /收集到水瓶怪人/);
  assert.match(game, /CollectionPopupState/);
  assert.match(game, /type GameState = "start" \| "playing" \| "win" \| "lose"/);
  assert.match(game, /GAME_DURATION_SECONDS = 180/);
  assert.match(game, /const \[timeLeft, setTimeLeft\] = useState\(GAME_DURATION_SECONDS\)/);
  assert.match(game, /const \[foundCount, setFoundCount\] = useState\(0\)/);
  assert.match(game, /const \[checkedWeirdos, setCheckedWeirdos\] = useState<WeirdoId\[\]>\(\[\]\)/);
  assert.match(game, /isTimerPaused/);
  assert.doesNotMatch(game, /playFailSound/);
  assert.match(game, /copyShareUrl/);
  assert.match(game, /miniMap/);
  assert.match(game, /miniMapZones/);
  assert.match(game, /miniMapRoads/);
  assert.match(game, /worldToMiniMapY/);
  assert.doesNotMatch(game, /updateFoundWeirdoFollower/);
  assert.match(game, /虛空灌籃高手/);
  assert.match(game, /量子燃脂傳教士/);
  assert.match(game, /外星迷因解碼器/);
  assert.match(game, /jumping-jack/);
  assert.match(game, /floor-crawl/);
  assert.match(game, /umbrella-receiver/);
  assert.match(game, /updateWeirdoBehavior/);
  assert.match(game, /mission-tracker/);
  assert.match(game, /時間倒數/);
  assert.match(game, /jumpPlatforms/);
  assert.match(game, /isOnWalkableSurface/);
  assert.match(game, /createSkyWorlds/);
  assert.match(game, /createFloatingVoxelIsland/);
  assert.match(game, /updateSkyCycle/);
  assert.match(game, /addVoxelCivicDetails/);
  assert.match(game, /addExpandedVoxelLife/);
  assert.match(game, /AQUARIUS_CASCADE_INSTALLATION_TARGET_HEIGHT = 7/);
  assert.match(game, /fitCityAssetToWorldHeight/);
  assert.match(game, /OBJLoader/);
  assert.match(game, /MTLLoader/);
  assert.match(game, /model\.fbm\/base_color\.jpg/);
  assert.doesNotMatch(game, /central-ring-fountain/);
  assert.match(game, /EXTRA_COMMUNITY_HOUSES/);
  assert.match(game, /EXTRA_TREE_SPECS/);
  assert.match(game, /AQUARIUS_ANIMALS/);
  assert.match(game, /逆向咩咩/);
  assert.match(game, /paverCount/);
  assert.match(game, /doorLintel/);
  assert.match(game, /lowerBowl/);
  assert.match(game, /clearRuntimeInteractionState/);
  assert.match(game, /resumeRuntimeInteractionModal/);
  assert.match(game, /正在前往霓虹浮島\.\.\./);
  assert.match(game, /Jay Peng Made 👽/);
  assert.match(game, /觀測紀錄/);
  assert.doesNotMatch(game, /水瓶圖鑑/);
  assert.doesNotMatch(game, /OBSERVATION COMPLETE/);
  assert.match(game, /挑戰成功/);
  assert.match(game, /霓虹浮島的能量已成功控制/);
  assert.match(game, /weirdo_5_gravity_spinner_custom_v3\.glb/);
  assert.match(game, /weirdo_7_tree_hugger_custom_v3\.glb/);
  assert.match(game, /Indoor_Swing/);
  assert.match(game, /Slow_Ladder_Climb/);
  assert.match(game, /applyEmbeddedWeirdoVisualPose/);
  assert.match(game, /createEmbeddedWeirdoSafetyFallback/);
  assert.match(game, /shouldUseEmbeddedWeirdoFallback/);
  assert.match(game, /normalizeEmbeddedWeirdoClip/);
  assert.match(game, /track\.name === "Hips\.position"/);
  assert.match(game, /values\[index \+ 1\] = 0/);
  assert.match(game, /CUSTOM_EMBEDDED_WEIRDO_TARGET_HEIGHT = PLAYER_RUNTIME_TARGET_HEIGHT/);
  assert.match(game, /CUSTOM_EMBEDDED_WEIRDO_GROUND_Y_BY_ID/);
  assert.match(game, /weirdo_5:\s*0\.04/);
  assert.match(game, /weirdo_7:\s*1\.18/);
  assert.match(game, /getCustomEmbeddedWeirdoGroundY/);
  assert.match(game, /TREE_HUGGER_CLIMB_X = 0\.92/);
  assert.match(game, /TREE_HUGGER_CLIMB_Z = -0\.08/);
  assert.match(game, /TREE_HUGGER_CLIMB_ROTATION_Y = Math\.PI \+ 0\.72/);
  assert.match(game, /function lockCustomEmbeddedActorToHeight/);
  assert.match(game, /function pinEmbeddedActorBottomYToLocalTarget/);
  assert.match(game, /targetHeight: CUSTOM_EMBEDDED_WEIRDO_TARGET_HEIGHT/);
  assert.match(game, /preciseBox: true/);
  assert.match(game, /groundModelToFloor\(THREE_REF, actorModel, 0, usesCustomEmbeddedWeirdo\)/);
  assert.match(game, /groundModelToFloor\(THREE_REF, model, 0, options\.preciseBox === true\)/);
  assert.match(game, /customEmbeddedRuntimeLocked/);
  assert.match(game, /actorRoot\.position\.copy\(target\)/);
  assert.match(game, /position:\s*\[12\.6,\s*0,\s*11\.8\]/);
  assert.doesNotMatch(game, /\{ x: 12\.6, z: 11\.8, width: 1\.9/);
  assert.doesNotMatch(game, /usesManualSafeEmbeddedPose/);
  assert.match(game, /const mustUseCustomModel = weirdo\.id === "weirdo_5" \|\| weirdo\.id === "weirdo_7"/);
  assert.match(game, /const usePreciseCustomBox = rule\.preciseBox \?\? false/);
  assert.match(game, /mustUseCustomModel && weirdo\.id === "weirdo_5"/);
  assert.match(game, /pinEmbeddedActorBottomYToLocalTarget\(THREE_REF, group, actorRoot, target, usePreciseCustomBox\)/);
  assert.match(game, /pinEmbeddedActorBoxToLocalTarget\(THREE_REF, group, actorRoot, target, usePreciseCustomBox\)/);
  assert.doesNotMatch(game, /targetHeight: 1\.28/);
  assert.doesNotMatch(game, /const safetyFallback = createEmbeddedWeirdoSafetyFallback/);
  assert.match(game, /setEmbeddedWeirdoSafetyFallback\(group, true\)/);
  assert.match(game, /maxDimension < 0\.38/);
  assert.match(game, /maxDimension > rule\.maxDimension \* 1\.9/);
  assert.doesNotMatch(game, /sourceDimension < rule\.targetDimension \* 0\.62/);
  assert.match(game, /pinEmbeddedActorBoxToLocalTarget/);
  assert.match(game, /outcome-overlay/);
  assert.match(game, /島嶼已被怪異腦波淹沒/);
  assert.match(game, /我不服！再試一次！/);
  assert.match(game, /水瓶座統治了世界！從今天起你也是水瓶座/);
  assert.match(game, /再玩一次/);
  assert.match(game, /share-link/);
  assert.match(css, /\.story-screen/);
  assert.match(css, /\.story-chapter/);
  assert.match(css, /\.story-page-actions/);
  assert.match(css, /\.story-arrow-button/);
  assert.match(css, /\.marquee-track/);
  assert.match(css, /\.sound-icon/);
  assert.match(css, /sound-on-home\.png/);
  assert.match(css, /sound-off-home\.png/);
  assert.match(css, /jump-person\.png/);
  assert.match(css, /\.avatar-mobile-switcher/);
  assert.match(css, /\.avatar-cycle-button/);
  assert.match(css, /\.mobile-action\.visible/);
  assert.match(css, /\.desktop-key-hint/);
  assert.match(css, /\.mobile-joystick\.hidden/);
  assert.match(css, /\.minimal-hud\s*\{\s*display:\s*none;/);
  assert.match(css, /CIQUTA/);
  assert.match(css, /\.intro-audio-control/);
  assert.match(css, /\.collection-popup/);
  assert.match(css, /\.mini-map/);
  assert.match(css, /\.mini-map-zone/);
  assert.match(css, /\.mini-map-road/);
  assert.match(css, /\.share-link/);
  assert.match(css, /\.quality-toggle/);
  assert.match(css, /\.shortcut-help/);
  assert.match(css, /\.mission-tracker/);
  assert.match(css, /\.outcome-overlay\.lose::before/);
  assert.match(css, /glitch-scan/);
  assert.match(layout, /title:\s*"Find Weirdo"/);
  assert.match(page, /<AquariusGame \/>/);
  assert.match(gameData, /0號觀測特工/);
  assert.match(gameData, /電光像素浪人/);
  assert.match(gameData, /霓虹矩陣暴走姬/);
  assert.match(gameData, /代號：404 異星體/);
  assert.match(gameData, /作者本人/);
  assert.match(gameData, /Jay Peng \/ 27歲 \/ 男性/);
  assert.match(gameData, /author-agree\.glb/);
  assert.doesNotMatch(gameData, /runtimeProcedural: true/);
  assert.match(gameData, /proceduralOnly: true/);
  assert.match(gameData, /facingOffset: 0/);
  assert.doesNotMatch(gameData, /facingOffset: Math\.PI/);
  assert.match(css, /avatar-head\[data-avatar="author-self"\]/);
  assert.match(layout, /viewportFit:\s*"cover"/);
  assert.match(cityLayout, /aquarius-cascade-installation/);
  assert.match(cityLayout, /aquarius-pour/);
  assert.match(cityLayout, /Meshy_AI_Aquarius_Pour_0722135912_texture\.obj/);
  assert.match(cityLayout, /AQUARIUS_CASCADE_INSTALLATION_ASSET/);
  assert.match(cityLayout, /MESHY_INSTALLATION_ART_TARGET_HEIGHT = 2\.5/);
  assert.match(cityLayout, /meshy-azure-vessel-art/);
  assert.match(cityLayout, /Meshy_AI_Azure_Vessel_with_Gol_0722171839_texture\.obj/);
  assert.match(cityLayout, /meshy-gate-of-future-art/);
  assert.match(cityLayout, /Meshy_AI_Gate_of_the_Future_0722171537_texture\.obj/);
  assert.match(cityLayout, /meshy-voxel-cascade-art/);
  assert.match(cityLayout, /Meshy_AI_Voxel_Cascade_0722115040_texture\.obj/);
  assert.match(cityLayout, /targetHeight: MESHY_INSTALLATION_ART_TARGET_HEIGHT/);
  assert.doesNotMatch(cityLayout, /civic-aquarius-tower/);
  assert.doesNotMatch(cityLayout, /plaza-fountain/);

  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
  assert.doesNotMatch(page, /_sites-preview|SkeletonPreview|codex-preview/);
  assert.doesNotMatch(layout, /Starter Project|codex-preview/);
});
